# Generated by Django 2.2.8 on 2023-01-25 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('institution', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('lastmodified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'collisions',
            },
        ),
        migrations.CreateModel(
            name='CollisionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('iaea_code', models.CharField(error_messages={'unique': 'This code is already associated with another collision type'}, max_length=64, null=True, unique=True)),
                ('vamdc_code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collisiontypes',
            },
        ),
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('data_values', models.TextField(blank=True, help_text='Space delimited values', null=True)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('parameter', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'datalists',
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('collision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='node.Collision')),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('inchi', models.CharField(max_length=256)),
                ('inchikey', models.CharField(max_length=128)),
                ('chemical_formula', models.CharField(max_length=128)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_node.species_set+', to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='SpeciesState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_node.speciesstate_set+', to='contenttypes.ContentType')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.Species')),
            ],
            options={
                'db_table': 'speciesstates',
            },
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('species_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='node.Species')),
                ('nuclear_charge', models.CharField(blank=True, max_length=32, null=True)),
                ('ion_charge', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Atoms',
                'db_table': 'atoms',
            },
            bases=('node.species',),
        ),
        migrations.CreateModel(
            name='AtomicState',
            fields=[
                ('speciesstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='node.SpeciesState')),
                ('qn', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_electrons', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'atomicstates',
            },
            bases=('node.speciesstate',),
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('species_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='node.Species')),
                ('cas', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name_plural': 'Molecules',
                'db_table': 'molecules',
            },
            bases=('node.species',),
        ),
        migrations.CreateModel(
            name='TabulatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='node.DataSet')),
                ('x', models.ManyToManyField(related_name='tabulated_data_x', to='node.DataList')),
                ('y', models.ManyToManyField(related_name='tabulated_data_y', to='node.DataList')),
            ],
            options={
                'verbose_name_plural': 'Tabulated data',
                'db_table': 'tabulateddata',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('book', 'book'), ('database', 'database'), ('journal', 'journal'), ('preprint', 'preprint'), ('proceedings', 'proceedings'), ('report', 'report'), ('thesis', 'thesis'), ('private communication', 'private communication'), ('vamdc node', 'vamdc node')], default='journal', max_length=32)),
                ('article_number', models.CharField(blank=True, help_text='Article number, journal-specific article identifier, may contain any string', max_length=128, null=True)),
                ('digital_object_id', models.CharField(blank=True, help_text='Digital Object Identifier. Example: doi:10.1016/j.adt.2007.11.003', max_length=128, null=True)),
                ('title', models.CharField(help_text='Title', max_length=128)),
                ('source_id', models.CharField(blank=True, max_length=128, null=True)),
                ('publisher', models.CharField(blank=True, help_text='Publisher of a bibliographic reference. Example: IOP Publishing Ltd', max_length=256, null=True)),
                ('uri', models.CharField(blank=True, help_text='A Uniform Resource Identifier of a bibliographic reference. Example: http://www.iop.org/EJ/abstract/0953-4075/41/10/105002', max_length=256, null=True)),
                ('page_begin', models.CharField(blank=True, help_text='Initial page of a bibliographic reference. Example: 22', max_length=16, null=True)),
                ('page_end', models.CharField(blank=True, help_text='Final page of a bibliographic reference. Example: 23', max_length=16, null=True)),
                ('volume', models.CharField(blank=True, help_text='Volume of the bibliographic reference. Example: 72A', max_length=128, null=True)),
                ('source_name', models.CharField(blank=True, help_text='Bibliographic reference name. Example: Physical Review', max_length=256, null=True)),
                ('bibtex', models.CharField(blank=True, help_text='BibTeX representation of reference, for those who already have it in database', max_length=1024, null=True)),
                ('comments', models.CharField(blank=True, max_length=1024, null=True)),
                ('year', models.CharField(blank=True, max_length=16, null=True)),
                ('authors', models.ManyToManyField(related_name='sources', to='node.Author')),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='sources',
            field=models.ManyToManyField(related_name='data_sets', to='node.Source'),
        ),
        migrations.AddField(
            model_name='collision',
            name='collision_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.CollisionType'),
        ),
        migrations.AddField(
            model_name='collision',
            name='products',
            field=models.ManyToManyField(related_name='products', to='node.SpeciesState'),
        ),
        migrations.AddField(
            model_name='collision',
            name='reactants',
            field=models.ManyToManyField(related_name='reactants', to='node.SpeciesState'),
        ),
        migrations.CreateModel(
            name='MolecularState',
            fields=[
                ('speciesstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='node.SpeciesState')),
                ('n', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('l', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('energy', models.CharField(blank=True, max_length=128, null=True)),
                ('energy_unit', models.CharField(blank=True, max_length=32, null=True)),
                ('auxillary', models.BooleanField(blank=True)),
                ('energy_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='node.MolecularState')),
            ],
            options={
                'db_table': 'molecularstates',
            },
            bases=('node.speciesstate',),
        ),
    ]
