# Generated by Django 2.2.8 on 2023-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atom',
            name='ion_charge',
        ),
        migrations.RemoveField(
            model_name='atom',
            name='nuclear_charge',
        ),
        migrations.RemoveField(
            model_name='molecule',
            name='cas',
        ),
        migrations.AddField(
            model_name='species',
            name='cas',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='ion_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='nuclear_charge',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
