# Generated by Django 2.2.8 on 2023-01-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20230126_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecularstate',
            name='auxillary',
        ),
        migrations.RemoveField(
            model_name='molecularstate',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='molecularstate',
            name='energy_origin',
        ),
        migrations.RemoveField(
            model_name='molecularstate',
            name='energy_unit',
        ),
        migrations.RemoveField(
            model_name='molecularstate',
            name='l',
        ),
        migrations.RemoveField(
            model_name='molecularstate',
            name='n',
        ),
    ]
