# Generated by Django 2.2.8 on 2023-01-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_auto_20230126_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atomicstate',
            name='number_of_electrons',
        ),
    ]
