# Generated by Django 2.2.8 on 2023-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_remove_atomicstate_number_of_electrons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(help_text='Title', max_length=256),
        ),
    ]
