# Generated by Django 2.2.8 on 2023-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_auto_20230606_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='nuclear_charge',
        ),
        migrations.AddField(
            model_name='atom',
            name='nuclear_charge',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
