# Generated by Django 2.2.8 on 2026-04-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_auto_20230623_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atom',
            name='nuclear_charge',
        ),
        migrations.AddField(
            model_name='species',
            name='molecular_weight',
            field=models.FloatField(blank=True, error_messages={'invalid': 'Please enter a valid float number'}, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='nuclear_charge',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='stoichiometric_formula',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
