# Generated by Django 2.2.8 on 2026-04-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_auto_20260423_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabulateddata',
            name='collision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='node.Collision'),
        ),
    ]
