# Generated by Django 2.2.8 on 2026-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_tabulateddata_collision'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('collisions', models.ManyToManyField(related_name='data_sources', to='node.Collision')),
                ('sources', models.ManyToManyField(related_name='data_sources', to='node.Source')),
            ],
            options={
                'db_table': 'datasources',
            },
        ),
    ]
