# Generated by Django 2.2.8 on 2026-04-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_datasource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabulateddata',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
    ]
