# Generated by Django 2.2.8 on 2026-06-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_auto_20260428_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabulateddata',
            options={},
        ),
        migrations.AddField(
            model_name='collisiontype',
            name='has_electron_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collisiontype',
            name='has_electron_reactant',
            field=models.BooleanField(default=False),
        ),
    ]
